### ISSUE TITLE
Endpoint | "add team" email

### ISSUE THREAD

**Issue by whroman** [xmunoz/uwrtourist#10]
We need a way to send an email to web admins with all of the information contained within "Add Team" form.

**Comment by xmunoz** [comment]
The endpoint works and the email is getting sent. What I still think we need is some backend validation (for people just hitting the endpoint programmatically instead of through the form), and then a way for admins to approve the submission (so maybe another view?). Here is what I propose:

Add a `status` column to the `teams` table, that can have one of 3 states: active, pending, inactive. After the data passes backend validation, then it will automatically get added to the database with the `pending` flag. This means that the data will only be viewable by admins. Admins can then either edit the data, delete if (if it's just garbage that a bot added), or approve it, which would set the status field to `active`.

**Comment by whroman** [comment]
Sounds good to me. This may be obvious, but let's be sure to write the delete/activate/suspend team endpoints in a way that they only work with Admins. If I understand correctly, an Admin is defined as someone that has passed a basic-auth gate, correct?)

**Comment by xmunoz** [comment]
Yep, and the basic auth gate is now up. I'll add some routes for admin.
